add babel-plugin-import for ui
kupibilet-frontend/babel-preset-kupibilet pull request #11
Opened 2019-06-06 16:19 UTC by yulya9060

2019-06-13 08:38 UTC, loonywizard submitted a review, later dismissed
Вроде всё в порядке, аппрув)

2019-06-17 15:42 UTC, nezed requested changes

2019-06-17 15:42 UTC, nezed commented on generateConfig.js
> +    }],
Почему везде есть третий эл-т в массиве, а здесь нет?

2019-06-17 15:42 UTC, nezed commented on generateConfig.js
> +    },'@kupibilet/ui/utils'],
Выглядит что все три конфига идентичны, кроме двух моментов. Стоит упростить.
Уже сейчас тут можно визуально упустить ошибку

2019-06-19 09:25 UTC, yulya9060 commented on generateConfig.js
> +    }],
так как он идет первым, то для него не нужно уникальное имя(для этого пресета), а вот для остальных уже нужно. Но добавлю, чтобы было одинаково

2019-06-20 17:44 UTC, nezed commented on parts/plugins/ui-kit-import.js
> +]
@yulya9060 Как тебе такой подход?

2019-06-20 17:46 UTC, nezed approved these changes

2019-06-20 17:46 UTC, merged